version: "2"
services:
  mariadb:
    image: mariadb:10.4.8
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=tortue
      - TZ=Europe/London
      - MYSQL_DATABASE=seeds
      - MYSQL_USER=seeds
      - MYSQL_PASSWORD=tortue
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - /db/volume:/config/databases

networks:
  default:
    external:
      name: db-web
